version: "3"

services:
  # api
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/api/data
  
  # ReactJS app
  react-app:
    build:
      context: .
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
