# Use an official Node.js runtime as a base image
FROM node:14

# Set the working directory in the container
WORKDIR /api

# Copy package.json and package-lock.json to the working directory
COPY ./frontend/react_fastapi_app/package*.json ./

# Install dependencies
RUN npm install

# Copy the local React app files to the working directory
COPY ./frontend/react_fastapi_app ./

# Expose port 3000
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]